#!/usr/bin/env bash
# Changes localhost and facebook.com IP mappings in /etc/hosts

echo "Updating /etc/hosts to assign 127.0.0.2 to localhost and 8.8.8.8 to facebook.com"

sudo sed -i '/127.0.0.1\s\+localhost/d' /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
